# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json yarn.lock tsconfig.json tsup.config.ts ./
COPY src ./src
RUN yarn install --frozen-lockfile && yarn build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy package.json and install production dependencies only
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile

# Copy built files
COPY --from=builder /app/lib ./lib

# Set environment
ENV NODE_ENV=production

# Start command
CMD ["node", "-r", "dotenv/config", "lib/index.js"]
